.\"Copyright (c) 2026, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"* Neither the name of the copyright holder nor the names of its
.\"  contributors may be used to endorse or promote products derived from
.\"  this software without specific prior written permission.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd September 30, 2026
.Dt JTRANSFER 1
.Os
.Sh NAME
.Nm jtransfer
.Nd securely transfer files between jails
.Sh SYNOPSIS
.Nm
.Fl v
.Nm
.Op Fl r Ns | Ns Fl w
.Op Fl h
.Op Fl m Ar mode
.Op Fl u Ar uid Ns Oo Ns : Ns Ar gid Oc
.Fl f Ar file
.Fl j Ar jid
.Sh DESCRIPTION
.Nm
is a lightweight tool for reading a file from a FreeBSD jail and writing
it to standard output, or for reading from standard input and writing the
content as a file inside a FreeBSD jail. The transfer is implemented
essentially using a standard
.Xr pipe 2 Ns ,
following the typical Unix way.
.Pp
This is very different from other approaches you are likely familiar with:
.Pp
.Bl -tag -width xxx
.It Transfer a file via SSH
This requires the jail to have an SSH implementation up and running, with
SFTP configured, as well as an allowed user within the jail and other fun
stuff related to keys or passwords, depending on how the daemon is configured.
It is a suitable solution for transferring files between hosts, but it is
overly complex if the goal is simply to transfer a file locally.
.It Transfer a file by executing a command in the jail directory
This is the standard approach taken by most jail tools, but it relies on
the premise that the jail itself has not been compromised. However, even
the root user could be compromised; therefore, files could be altered even
if they are managed exclusively by the root user. At a minimum, jail tools
should offer an option to prevent following symbolic links in case they are
malicious.
.Pp
.Nm
does not offer a magic solution for dealing with altered files; however, when
using
.Xr cp 1 Ns ,
.Xr tar 1 Ns ,
or any other command to transfer a file, you must keep in mind that you
are executing them from the host. Unlike those commands,
.Nm
runs inside a jail; always. Furthermore, unlike standard commands, there
is no need to deal with relative paths when writing the file, as the
command executes within the specific jail you specify.
.It Transfer a file using Xr sh 1 No and Xr cat 1
Running
.Ql jexec -l Ar jail No sh -c "cat > /path/to/file"
inside a FreeBSD jail is similar in style to
.Nm Ns "."
However, this introduces two dependencies. In most cases, this poses no
problem; however, if the jail is very minimal, for example, if it contains
only a static binary and the files it requires, this is not the right solution.
.Pp
In reality, the internal operation of
.Nm
much more closely resembles that of
.Xr cp 1
than that of
.Xr cat 1 Ns "."
.El
.Pp
The internal operation of
.Nm
is very similar to that of
.Xr cp 1 Ns ,
although its usage resembles that of
.Xr cat 1 Ns "."
This means you have a command that is just as efficient as the standard
.Xr cp 1 Ns "."
However, unlike
.Xr cp 1 Ns ,
.Nm
cannot use
.Xr copy_file_range 2 Ns ,
so the file is copied using a more traditional approach, even if you are
using ZFS as your file system.
.Pp
The options are as follows:
.Pp
.Bl -tag -width xxx
.It Fl h
No symbolic links are followed.
.It Fl r
Read mode.
.Pp
The file specified with the
.Fl f
option is read inside the jail and written to standard output.
.It Fl w
Write mode.
.Pp
The content is read from standard input and written to the file specified
with the
.Fl f
option.
.It Fl m Ar mode
File mode.
.Pp
.Xr umask 2
is ignored. The file mode specified here will be applied to the created file.
.It Fl u Ar uid Ns Oo : Ns Ar gid Oc
Drop privileges after entering the jail.
.It Fl f Ar file
File path.
.It Fl j Ar jid
Perform the actions inside the jail specified by
.Ar jid Ns ,
which may be either a jail name or a numeric jail ID.
.El
.Sh EXAMPLES
.Ss Read a file from the jail
.Bd -literal -offset indent
# jtransfer -r -f /etc/rc.conf -j x11appjail-thunderbird-15000_default
clear_tmp_X="NO"
ifconfig_eb_ec6e1439cb6="inet 10.0.0.4 netmask 255.192.0.0 broadcast 10.63.255.255"
defaultrouter="10.0.0.1"
dbus_enable="YES"
.Ed
.Ss Write a file from the jail to the host
.Bd -literal -offset indent
# jtransfer -r -f hello.txt -j x11appjail-thunderbird-15000_default > hello.txt
.Ed
.Ss Write a file from the host to the jail
.Bd -literal -offset indent
# cat hello.txt | jtransfer -w -f hello.txt -j x11appjail-thunderbird-15000_default
# jtransfer -r -f hello.txt -j x11appjail-thunderbird-15000_default
Hello, world!
.Ed
.Ss Write a file from the jail to another jail
.Bd -literal -offset indent
# jtransfer -r -f /etc/hosts -j x11appjail-thunderbird-15000_default |\e
    jtransfer -w -j x11appjail-telegram-desktop-15000_default -f /etc/hosts
.Ed
.Sh SEE ALSO
.Xr chmod 1
.Xr jail 3
.Xr sysexits 3
.Sh AUTHORS
.An Jesús Daniel Colmenares Oviedo Aq Mt DtxdF@disroot.org
